#!/usr/bin/env bash

LC_ALL=C
LANG=C

schermi=$(xrandr | awk '/\<connected\>/{ print $1}')

for i in $schermi;
	do screen=$(find ~/wallpapers -type f |sort -R |tail -n1);
	arg+=(--output "$i" --stretch "$screen");
done

xwallpaper "${arg[@]}"
